language: node_js
node_js:
  - 12.4.0
cache: npm
install:
  - travis_wait npm install -g npm@latest --save react react-dom react-scripts
script:
  - travis_wait npm start
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
