language: node_js
node_js:
  - 12.4.0
cache: npm
install:
  - npm install --save react react-dom react-scripts
script:
  - npm start
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
